### ISSUE TITLE
Spelling/grammar mistake in geodesic.cu

### ISSUE THREAD

**Issue by bradphelan** [owensgroup/RXMesh#14]
https://github.com/owensgroup/RXMesh/blob/54f29b3e2b8f020a9d5e89f94002fdcc5273d124/apps/Geodesic/geodesic.cu#L88

> Display this masage and exits

should read

> Display this message and exit

 > Input file. Input file should under the input/ subdirectory\n"

should read

>  Input file. Input file should exist under the input/ subdirectory\n"

**Comment by Ahdhn** [comment]
Thanks @bradphelan for bringing this up to our attention! It is fixed and will be part of the next release.
