### ISSUE TITLE
like mesh hole filling or simplification works well?

### ISSUE THREAD

**Issue by nashdingsheng** [owensgroup/RXMesh#2]
Dear  Ahdhn,  i want to consult you again whether this gpu data structure works well and conveniently implemented  for the algorithms like mesh hole filling or simplification which will change the topology of the original mesh. I do not need to change the original mesh itself or related patched information  at real time while  the algorithm is running ,  but  just want to save the result mesh with changed topology in a object whose class is  RXMESH::RXMeshAttribute<T>.  after this algorithm,  i then do  partition again of the topology changed mesh to run another algorithm. though i have noticed the limitations that dynamic scene is not appropriate mentioned in your paper, but just want to confirm it again,  thank you .

**Comment by Ahdhn** [comment]
As of right now, topology changes are not supported either doing these changes concurrently on the GPU or just saving them and then rebuilding the data structure (i.e., re-patching). This is the focus of our current investigation and so expect it to come in the future releases 🤞🏽

**Comment by nashdingsheng** [comment]
ok，i got it, thank you.
