### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [owensgroup/RXMesh#35]
Hi team,

searching for a robust GPU-based mesh data structure, I found RXMesh and wanted to inquire about the development status. I can see some work being done in dedicated branches but am not sure how advanced this is and whether the library is ready for any production purposes. 

I'm interested in mesh booleans, hole-filling, generating mesh contours, etc.

Would be great to hear about your plans!

**Comment by Ahdhn** [comment]
Hi @mariuszhermansdorfer 

Thank you for your interest! 

We are working on implementing more of these "dynamic" applications (those that change the mesh topology). Right now, our focus is on dynamic applications that require "local" updates (e.g., mesh simplification, isotropic remeshing, Delaunay refinement) where the update operations are something like edge flip, edge collapse, and vertex split.  Mesh booleans and hole-filling sound like interesting applications that we will consider.
