### ISSUE TITLE
unknown file: error: C++ exception with description "Polyscope has not been initialized" thrown in the test body.

### ISSUE THREAD

**Issue by imTequila** [owensgroup/RXMesh#37]
when i run rxmesh_test, 
i got error:     unknown file: error: C++ exception with description "Polyscope has not been initialized" thrown in the test body.
and polyscope_test is ok   
![image](https://github.com/user-attachments/assets/9038e1e0-ddc9-4e09-ac6c-65a31f42b159)

**Comment by Ahdhn** [comment]
Hi @imTequila,

Thank you for reporting the error. It looks like you are using the `dyn` branch. I have just run `RXMesh_test` for this branch on my Windows machine using Visual Studio 2022 and WSL, and everything ran smoothly.

Could you please provide more details about your system specifications (compiler, CUDA version, GPU)?

I suggest isolating the failing test using the `--gtest_filter` option. Since the first failed test is `RXMeshStatic.ForEach`, try running the following command:

```
./RXMesh_test --gtest_filter=RXMeshStatic.ForEach
```
Please let me know if the error persists.

**Comment by imTequila** [comment]
> Hi @imTequila,
> 
> Thank you for reporting the error. It looks like you are using the `dyn` branch. I have just run `RXMesh_test` for this branch on my Windows machine using Visual Studio 2022 and WSL, and everything ran smoothly.
> 
> Could you please provide more details about your system specifications (compiler, CUDA version, GPU)?
> 
> I suggest isolating the failing test using the `--gtest_filter` option. Since the first failed test is `RXMeshStatic.ForEach`, try running the following command:
> 
> ```
> ./RXMesh_test --gtest_filter=RXMeshStatic.ForEach
> ```
> 
> Please let me know if the error persists.

Thank you for your suggestion, but my problem still exists.
Im using the `main` branch, and my env is:

Visual Studio 2019
Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22631.
The C compiler identification is MSVC 19.29.30154.0
The CXX compiler identification is MSVC 19.29.30154.0
The CUDA compiler identification is NVIDIA 12.0.76
GPU NVIDIA 4060 laptop

when i run  `--gtest_filter=RXMeshStatic.ForEach`
i got this
[08:56:42] RXMesh: input= E:/CGLearning/RXMesh/input/sphere3.obj
[08:56:42] RXMesh: output_folder= E:/CGLearning/RXMesh/output/
[08:56:42] RXMesh: num_run= 1
[08:56:42] RXMesh: device_id= 0
Note: Google Test filter = RXMeshStatic.ForEach
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from RXMeshStatic
[ RUN      ] RXMeshStatic.ForEach
[08:56:42] RXMesh: Total number of device: 1
[08:56:42] RXMesh: Using device Number: 0
[08:56:42] RXMesh: Device name: NVIDIA GeForce RTX 4060 Laptop GPU
[08:56:42] RXMesh: Compute Capability: 8.9
[08:56:42] RXMesh: Total amount of global memory (MB): 8187.5
MapSMtoCores for SM 8.9 is undefined.  Default to use 128 Cores/SM
MapSMtoCores for SM 8.9 is undefined.  Default to use 128 Cores/SM
[08:56:42] RXMesh: 24 Multiprocessors, 128 CUDA Cores/MP: 3072 CUDA Cores
[08:56:42] RXMesh: ECC support: Disabled
[08:56:42] RXMesh: GPU Max Clock rate: 2250.0 MHz (2.25 GHz)
[08:56:42] RXMesh: Memory Clock rate: 8001.0 Mhz
[08:56:42] RXMesh: Memory Bus Width:  128-bit
[08:56:42] RXMesh: Peak Memory Bandwidth: 256.032000(GB/s)
[08:56:42] RXMesh: Kernels compiled for compute capability: 890
[08:56:42] RXMesh: Reading E:/CGLearning/RXMesh/input/cube.obj
[08:56:42] RXMesh: import_obj() #vertices= 8
[08:56:42] RXMesh: import_obj() #faces= 12
[08:56:42] RXMesh: import_obj() #tex= 0
[08:56:42] RXMesh: import_obj() #face_tex= 12
[08:56:42] RXMesh: import_obj() #normals = 0
[08:56:42] RXMesh: import_obj() #face_normal= 12
[08:56:42] RXMesh: Patcher: num_patches = 1
[08:56:42] RXMesh: Patcher: patches_size = 512
[08:56:42] RXMesh: Patcher: num_components = 1
[08:56:42] RXMesh: Patcher: Num lloyd run = 0
[08:56:42] RXMesh: Patcher: Parallel patches construction time = 0 (ms) and -nan (ms/lloyd_run)
[08:56:42] RXMesh: Patcher: max_patch_size= 12, min_patch_size= 12, avg_patch_size= 12
[08:56:42] RXMesh: Patcher: number external ribbon faces = 0 (0.00%)
[08:56:42] RXMesh: #Vertices = 8, #Faces= 12, #Edges= 18
[08:56:42] RXMesh: Input is  edge manifold
[08:56:42] RXMesh: Input is  closed
[08:56:42] RXMesh: max valence = 5
[08:56:42] RXMesh: max edge incident faces = 2
[08:56:42] RXMesh: max face adjacent faces = 3
[08:56:42] RXMesh: per-patch maximum face count = 12
[08:56:42] RXMesh: per-patch maximum edge count = 18
[08:56:42] RXMesh: per-patch maximum vertex count = 8
[08:56:42] RXMesh: per-patch maximum not-owned face count = 0
[08:56:42] RXMesh: per-patch maximum not-owned edge count = 0
[08:56:42] RXMesh: per-patch maximum not-owned vertex count = 0
unknown file: error: C++ exception with description "Polyscope has not been initialized" thrown in the test body.
[  FAILED  ] RXMeshStatic.ForEach (118 ms)
[----------] 1 test from RXMeshStatic (119 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (120 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RXMeshStatic.ForEach

 1 FAILED TEST

**Comment by imTequila** [comment]
> > Hi @imTequila,
> > Thank you for reporting the error. It looks like you are using the `dyn` branch. I have just run `RXMesh_test` for this branch on my Windows machine using Visual Studio 2022 and WSL, and everything ran smoothly.
> > Could you please provide more details about your system specifications (compiler, CUDA version, GPU)?
> > I suggest isolating the failing test using the `--gtest_filter` option. Since the first failed test is `RXMeshStatic.ForEach`, try running the following command:
> > ```
> > ./RXMesh_test --gtest_filter=RXMeshStatic.ForEach
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know if the error persists.
> 
> Thank you for your suggestion, but my problem still exists. Im using the `main` branch, and my env is:
> 
> Visual Studio 2019 Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22631. The C compiler identification is MSVC 19.29.30154.0 The CXX compiler identification is MSVC 19.29.30154.0 The CUDA compiler identification is NVIDIA 12.0.76 GPU NVIDIA 4060 laptop
> 
> when i run `--gtest_filter=RXMeshStatic.ForEach` i got this [08:56:42] RXMesh: input= E:/CGLearning/RXMesh/input/sphere3.obj [08:56:42] RXMesh: output_folder= E:/CGLearning/RXMesh/output/ [08:56:42] RXMesh: num_run= 1 [08:56:42] RXMesh: device_id= 0 Note: Google Test filter = RXMeshStatic.ForEach [==========] Running 1 test from 1 test suite. [----------] Global test environment set-up. [----------] 1 test from RXMeshStatic [ RUN ] RXMeshStatic.ForEach [08:56:42] RXMesh: Total number of device: 1 [08:56:42] RXMesh: Using device Number: 0 [08:56:42] RXMesh: Device name: NVIDIA GeForce RTX 4060 Laptop GPU [08:56:42] RXMesh: Compute Capability: 8.9 [08:56:42] RXMesh: Total amount of global memory (MB): 8187.5 MapSMtoCores for SM 8.9 is undefined. Default to use 128 Cores/SM MapSMtoCores for SM 8.9 is undefined. Default to use 128 Cores/SM [08:56:42] RXMesh: 24 Multiprocessors, 128 CUDA Cores/MP: 3072 CUDA Cores [08:56:42] RXMesh: ECC support: Disabled [08:56:42] RXMesh: GPU Max Clock rate: 2250.0 MHz (2.25 GHz) [08:56:42] RXMesh: Memory Clock rate: 8001.0 Mhz [08:56:42] RXMesh: Memory Bus Width: 128-bit [08:56:42] RXMesh: Peak Memory Bandwidth: 256.032000(GB/s) [08:56:42] RXMesh: Kernels compiled for compute capability: 890 [08:56:42] RXMesh: Reading E:/CGLearning/RXMesh/input/cube.obj [08:56:42] RXMesh: import_obj() #vertices= 8 [08:56:42] RXMesh: import_obj() #faces= 12 [08:56:42] RXMesh: import_obj() #tex= 0 [08:56:42] RXMesh: import_obj() #face_tex= 12 [08:56:42] RXMesh: import_obj() #normals = 0 [08:56:42] RXMesh: import_obj() #face_normal= 12 [08:56:42] RXMesh: Patcher: num_patches = 1 [08:56:42] RXMesh: Patcher: patches_size = 512 [08:56:42] RXMesh: Patcher: num_components = 1 [08:56:42] RXMesh: Patcher: Num lloyd run = 0 [08:56:42] RXMesh: Patcher: Parallel patches construction time = 0 (ms) and -nan (ms/lloyd_run) [08:56:42] RXMesh: Patcher: max_patch_size= 12, min_patch_size= 12, avg_patch_size= 12 [08:56:42] RXMesh: Patcher: number external ribbon faces = 0 (0.00%) [08:56:42] RXMesh: #Vertices = 8, #Faces= 12, #Edges= 18 [08:56:42] RXMesh: Input is edge manifold [08:56:42] RXMesh: Input is closed [08:56:42] RXMesh: max valence = 5 [08:56:42] RXMesh: max edge incident faces = 2 [08:56:42] RXMesh: max face adjacent faces = 3 [08:56:42] RXMesh: per-patch maximum face count = 12 [08:56:42] RXMesh: per-patch maximum edge count = 18 [08:56:42] RXMesh: per-patch maximum vertex count = 8 [08:56:42] RXMesh: per-patch maximum not-owned face count = 0 [08:56:42] RXMesh: per-patch maximum not-owned edge count = 0 [08:56:42] RXMesh: per-patch maximum not-owned vertex count = 0 unknown file: error: C++ exception with description "Polyscope has not been initialized" thrown in the test body. [ FAILED ] RXMeshStatic.ForEach (118 ms) [----------] 1 test from RXMeshStatic (119 ms total)
> 
> [----------] Global test environment tear-down [==========] 1 test from 1 test suite ran. (120 ms total) [ PASSED ] 0 tests. [ FAILED ] 1 test, listed below: [ FAILED ] RXMeshStatic.ForEach
> 
> 1 FAILED TEST

actually when i use `dyn` branch, everything is ok.

**Comment by Ahdhn** [comment]
I'm glad to hear that the issue is fixed! We plan to eventually merge `dyn` into `main`. Please feel free to report any other issues or ask any questions you may have. Thank you!
